FROM centos:7

WORKDIR /build
RUN yum -y update
RUN yum -y install epel-release yum-utils
RUN yum-config-manager --add-repo https://kojipkgs.fedoraproject.org/repos-dist/epel7Server-infra/latest/x86_64/
# TODO: Unpin the version of python-ldap3 after 2.5.2+ is released
RUN yum -y install \
    --nogpgcheck \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    bash \
    createrepo_c \
    fedmsg \
    fedmsg-hub \
    gcc \
    git \
    kobo \
    kobo-rpmlib \
    libmodulemd \
    python-backports-ssl_match_hostname \
    python-dogpile-cache \
    python-enum34 \
    python-flask \
    python-flask-migrate \
    python-flask-sqlalchemy \
    python-funcsigs \
    python-futures \
    python-koji \
    https://kojipkgs.fedoraproject.org//packages/python-ldap3/2.4/1.el7/noarch/python2-ldap3-2.4-1.el7.noarch.rpm \
    python-mock \
    python-munch \
    python-pip \
    python-prometheus_client \
    python-requests \
    python-six \
    python-solv \
    python-sqlalchemy \
    python2-pungi \
    # Test-only dependencies
    python-flake8 \
    python-mock \
    python-tox \
    rpm-build \
    && yum clean all
# We currently require newer versions of these Python packages for the tests.
# more-itertools is required by pytest, but versions 6.0.0 and up aren't Python 2 compatible
RUN pip install --upgrade flask-sqlalchemy pytest flake8 tox pip "more-itertools<6.0.0"
VOLUME /src
WORKDIR /src
CMD ["bash", "docker/test.sh"]
