FROM fedora:31

WORKDIR /build
RUN dnf -y install \
    --nogpgcheck \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    git-core \
    createrepo_c \
    rsync \
    python3-distro \
    python3-celery \
    python3-fedmsg \
    python3-kobo-rpmlib \
    python3-rpm \
    python3-gobject \
    python3-dnf \
    python3-dogpile-cache \
    python3-flask \
    python3-flask-migrate \
    python3-flask-sqlalchemy \
    python3-koji \
    python3-ldap3 \
    python3-libmodulemd \
    python3-munch \
    python3-pip \
    python3-prometheus_client \
    python3-requests \
    python3-six \
    python3-solv \
    python3-sqlalchemy \
    python3-pungi \
    python3-psycopg2 \
    python3-pytest-cov \
    # Test-only dependencies
    python3-pytest \
    python3-flake8 \
    python3-mock \
    python3-tox \
    rpm-build \
    python3-PyYAML \
    && dnf clean all
VOLUME /src
WORKDIR /src
ENTRYPOINT ["docker/test-py3.sh"]
