FROM fedora:29

WORKDIR /build
# Pin the version of libsolv until the following is in stable:
# https://bodhi.fedoraproject.org/updates/FEDORA-2019-c381c7bf54
RUN dnf -y install \
    --nogpgcheck \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    git-core \
    createrepo_c \
    python3-fedmsg \
    python3-kobo-rpmlib \
    python3-rpm \
    libmodulemd \
    python3-gobject \
    python3-dnf \
    python3-dogpile-cache \
    python3-flask \
    python3-flask-migrate \
    python3-flask-sqlalchemy \
    python3-koji \
    python3-ldap3 \
    python3-munch \
    python3-pip \
    python3-prometheus_client \
    python3-requests \
    python3-six \
    https://kojipkgs.fedoraproject.org//packages/libsolv/0.7.4/2.fc29/x86_64/libsolv-0.7.4-2.fc29.x86_64.rpm \
    https://kojipkgs.fedoraproject.org//packages/libsolv/0.7.4/2.fc29/x86_64/python3-solv-0.7.4-2.fc29.x86_64.rpm \
    python3-sqlalchemy \
    python3-pungi \
    # Test-only dependencies
    python3-pytest \
    python3-flake8 \
    python3-mock \
    python3-tox \
    rpm-build \
    python3-PyYAML \
    && dnf clean all
VOLUME /src
WORKDIR /src
CMD ["bash", "docker/test-py3.sh"]
