FROM fedora:29

WORKDIR /build
# Unpin the libmodulemd RPMs and replace with `python3-libmodulemd` after FEDORA-2019-b1cdf17e35
RUN dnf -y install \
    --nogpgcheck \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    git-core \
    createrepo_c \
    python3-fedmsg \
    python3-kobo-rpmlib \
    python3-rpm \
    python3-gobject \
    python3-dnf \
    python3-dogpile-cache \
    python3-flask \
    python3-flask-migrate \
    python3-flask-sqlalchemy \
    python3-koji \
    python3-ldap3 \
    https://kojipkgs.fedoraproject.org//packages/libmodulemd/2.4.0/1.fc29/x86_64/python3-libmodulemd-2.4.0-1.fc29.x86_64.rpm \
    https://kojipkgs.fedoraproject.org//packages/libmodulemd/2.4.0/1.fc29/x86_64/libmodulemd-2.4.0-1.fc29.x86_64.rpm \
    https://kojipkgs.fedoraproject.org//packages/libmodulemd/2.4.0/1.fc29/x86_64/libmodulemd1-1.8.10-1.fc29.x86_64.rpm \
    python3-munch \
    python3-pip \
    python3-prometheus_client \
    python3-requests \
    python3-six \
    python3-solv \
    python3-sqlalchemy \
    python3-pungi \
    # Test-only dependencies
    python3-pytest \
    python3-flake8 \
    python3-mock \
    python3-tox \
    rpm-build \
    python3-PyYAML \
    && dnf clean all
VOLUME /src
WORKDIR /src
CMD ["bash", "docker/test-py3.sh"]
